### PR TITLE
Github workflow with testing and code quality jobs

### PR DESCRIPTION
**Pull request by andrew-the-drawer**
## Related to: 
Resolve issue #8

## Description:
Create **github** workflow to automatically run unit test and pylint app 

## Tests:
Description of any tests you may have written to support this feature, if any. Tests are appreciated for all features of the app.

## Checklist:
Please put an x in each box that you have completed

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code in any hard-to-understand areas
- [x] My changes generate no new warnings or errors
- [x] I have added test instructions that prove my fix is effective or that my feature works

## Tasks:
- [x] Testing job
- [x] Linting job

### CODE REVIEW

**Comment by andrew-the-drawer** [comment]
I hope that this PR will be counted as my Hacktoberfest contribution according to [this new updates ](https://hacktoberfest.digitalocean.com/hacktoberfest-update)

**Review by capndave — COMMENTED** [review]
This looks awesome but I'm concerned about hard-coding the environment variables into the `ci.yml` file. Can that file access secrets that I've put in the github repo? If so we can update `ci.yml` with them and I'll add the necessary secrets.

**Comment by andrew-the-drawer** [comment]
> This looks awesome but I'm concerned about hard-coding the environment variables into the `ci.yml` file. Can that file access secrets that I've put in the github repo? If so we can update `ci.yml` with them and I'll add the necessary secrets.

Of course, you can. Take a look: [Sharing secrets in Github](https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets). 

Btw, pls send me the names and values of those secrets you intended to add so I can re-configurate the workflow.

P/S: Here, take a look at the result: 
image

**Comment by capndave** [comment]
Secret names are below. There's a small chance I have the wrong port in the secret but otherwise should work. 

DB_HOST_CLOUD
DB_NAME 
DB_PASSWORD 
DB_PORT 
DB_USER 
DJANGO_SECRET_KEY

**Comment by andrew-the-drawer** [comment]
Nice. Btw I don't think `DB_HOST_CLOUD` is useful for testing jobs, since all the services are initialized in the same network. Unless you want me to create a job for cloud deployment as well.... Please lemme know as soon as possible.

**Comment by capndave** [comment]
@lantrungseo my bad, changing it to DB_HOST now.

**Comment by andrew-the-drawer** [comment]
@capndave I have changed to secrets as you said. Please review!

**Review by capndave — APPROVED** [review]
Awesome. Thanks so much! This seems to be working!

**Pull request merged**
