### PR TITLE
Updated CONTRIBUTING.md

### LINKED ISSUE #53: Add clear guidelines to CONTRIBUTING.md to make it clear that a contributor must be assigned to an issue before submitting a pull request
## Type
Documentation update

## Problem or To-Do
Add clear guidelines to CONTRIBUTING.md to make it clear that a contributor must be assigned to an issue before submitting a pull request. The only exception to this rule should be for minor documentation updates. Feel free to word this however you feel is appropriate, capndave will review. Thanks!

### PR DESCRIPTION
**Pull request by saurabhhere**
## Related to:
Resolves: #53 

## Description:
Added guidelines to CONTRIBUTING.md for contributors to assigned them to issue before sending PR.

## Checklist:
Please put an x in each box that you have completed

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code in any hard-to-understand areas
- [x] My changes generate no new warnings or errors
- [] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by capndave — CHANGES_REQUESTED** [review]
Thanks for the submission! In order to make this a bit more clear (an in line with the incredibly specific requirements that I have but failed to mention in the issue), can you please replace lines 5-12 with the following:

### Submitting Issues

Please submit issues liberally. Since this application is under development you can feel free to add issues for any incomplete part of the application, as you imagine it would be implemented best.

### Documentation Updates

Minor changes to documentation can be submitted as a pull request without making an issue first.

### General Code Contributions

When contributing to this repository, please first discuss the change you wish to make in an [issue](https://github.com/capndave/gardenbuilder-frontend/issues). There are also a number of preexisting [issues](https://github.com/capndave/gardenbuilder-frontend/issues) that we would love your help with. Many of them are fairly easy and are tagged as `good first issue`. Most are things that we just haven't gotten around to yet. Before working on something, please:

- [x] Ensure that no one is working on the issue by checking that no one is listed in the Assignees field of a particular issue (generally on the upper-right hand corner of the issue screen)
- [x] If no contributor is already assigned, express your interest in working on the issue by writing a comment for that issue
- [x] Wait for a project maintainer to assign you the issue before you start working on it.

Generally speaking, the first person who expresses interest in working on an issue will be assigned. We may ignore pull requests from those who submit them without being assigned to work on the issue, particularly if someone else expressed interest in working on the issue before them.

Once you are assigned to work on an issue, please fork, work on it, and submit a pull request that references the related issue.

**Comment by saurabhhere** [comment]
Do I have to add till checkboxes or till the last paragraph?

**Comment by capndave** [comment]
'til the last paragraph, please

**Comment by saurabhhere** [comment]
@capndave Any more changes you want?

**Review by capndave — APPROVED** [review]
Thanks so much!

**Pull request merged**
