### PR TITLE
add tests for the sections app

### LINKED ISSUE #6: Write tests for Sections app
in pytest

### PR DESCRIPTION
**Pull request by Ryan104**
## Related to:
Resolves: #6 

## Description:
Added test coverage for the sections app. This includes the model, query, and mutation.

## Tests:
Added tests for model defaults and the graphql query and mutation

## Checklist:
Please put an x in each box that you have completed

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code in any hard-to-understand areas
- [x] My changes generate no new warnings or errors
- [x] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by capndave** [comment]
@Ryan104 I'm getting errors on `test_sections_query_without_data` and `test_sections_query_with_data`. Both throw and error similar to 
```bash
E       TypeError: object of type 'NoneType' has no len()
apps/sections/tests.py:91: TypeError
```
Do you mind taking a look at it again?

**Comment by Ryan104** [comment]
@capndave for sure!

**Comment by Ryan104** [comment]
~Hey @capndave , it looks like the api is now returning null (`None`) instead of empty list (`[]`) when there is no data. Is that expected? If so I can update the test. If not, I can look into the bug?~

Edit: Sorry I think I was looking at the wrong thing. I'll take another look quick.

**Comment by Ryan104** [comment]
I manually created a section through Graphiql and this query
```graphql
query {
  sections {
      id
  }
}
```

returns

```json
{
  "data": {
    "sections": null
  }
}
```

but it should return an array with a section in it instead of `None`.

@capndave if you want, you can create an issue and assign it to me?

**Comment by capndave** [comment]
Totally! Created issue #55 . I assigned it to myself so noone would take it, you need to make a comment on that issue before I can assign you. Please comment there and I'll assign you.

**Pull request merged**
