### PR TITLE
Changes Updated

### PR DESCRIPTION
**Pull request by Hinal-Srivastava**
Gardens model updated as required.
`garden_name` changed to `name`

### CODE REVIEW

**Comment by Hinal-Srivastava** [comment]
@capndave could you add the #hacktoberfest label to this. It will really help me out :)

**Comment by Hinal-Srivastava** [comment]
@capndave would be really great if you added the `hacktobefest-accepted` label! 🙂

**Comment by capndave** [comment]
Wow I swear I had added that label and now it's missing :unamused:

**Comment by Hinal-Srivastava** [comment]
> Wow I swear I had added that label and now it's missing :unamused: 

Hey that's alright. Thanks for adding it again!, 😄👍🏼

**Pull request merged**
